GET http://localhost:8080/
Content-Type: application/json

###
GET http://localhost:8080/products
Content-Type: application/json


###
GET http://localhost:8080/products/ed9f9bf7-e20d-4465-9d1c-bb1e08cf1399
Content-Type: application/json

###
PUT  http://localhost:8080/products/1
Content-Type: application/json

{
    "name" : "a",
    "description": "b"
}

###
POST  http://localhost:8080/products/
Content-Type: application/json

{
    "name" : "a",
    "description": "b"
}

###
DELETE http://localhost:8080/products/1
Content-Type: application/json